# Generated by Django 5.0.7 on 2024-07-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(auto_now=True, null=True, verbose_name='Время начала выполнения'),
        ),
    ]
