# Generated by Django 5.0.7 on 2024-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_check_periodicity_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время начала выполнения'),
        ),
    ]
