# Generated by Django 5.0.7 on 2024-07-17 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(15, 12, 57, 48707), null=True, verbose_name='Время начала выполнения'),
        ),
    ]
